esphome:
  name: boat-instruments
  includes:
    - seatalk.h

external_components:
  - source:
      type: local
      path: components

# ESP8266 with software serial on GPIO4/GPIO5
esp8266:
  board: nodemcuv2

# Enable logging but disable on UART
logger:
  baud_rate: 0  # Disable hardware serial logging
  level: DEBUG

# Software UART for SeaTalk
uart:
  id: seatalk_bus
  tx_pin: GPIO4    # Not actually used for RX-only, but required
  rx_pin: GPIO5    # SeaTalk data pin through voltage divider
  baud_rate: 4800
  data_bits: 8
  parity: NONE
  stop_bits: 1

# SeaTalk component
seatalk:
  id: my_seatalk
  uart_id: seatalk_bus
  update_interval: 60s  # Just for housekeeping

# Sensors
sensor:
  - platform: seatalk
    seatalk_id: my_seatalk
    depth:
      name: "Boat Depth"
      filters:
        - lambda: return x * -1;  # Depth is typically negative below water
    speed:
      name: "Boat Speed"
    wind_angle:
      name: "Apparent Wind Angle"
    wind_speed:
      name: "Apparent Wind Speed"
    heading:
      name: "Compass Heading"
    temperature:
      name: "Water Temperature"
    log_total:
      name: "Total Log"

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable Home Assistant API
api:

# OTA updates
ota:
