esphome:
  name: boat-instruments
  platform: ESP8266
  board: nodemcuv2

# Use the GitHub repository as external component
external_components:
  - source: github://twhtanghk/esphome-seatalk@main
    components: [seatalk]
    # Optional: if you want to use a specific commit instead of main branch
    # ref: 3e4dbf4  # You can specify a commit hash, tag, or branch

# Enable logging but disable on UART to avoid conflicts
logger:
  baud_rate: 0  # Disable hardware serial logging
  level: DEBUG

# Software UART for SeaTalk on ESP8266
# Using GPIO4/GPIO5 forces software serial since these aren't hardware UART pins
uart:
  id: seatalk_bus
  tx_pin: GPIO4    # Required but not used for RX-only
  rx_pin: GPIO5    # SeaTalk data pin through voltage divider (12V -> 3.3V)
  baud_rate: 4800
  data_bits: 8
  parity: NONE
  stop_bits: 1

# SeaTalk component
seatalk:
  id: my_seatalk
  uart_id: seatalk_bus
  update_interval: 60s  # Housekeeping interval, messages are processed in real-time

# Sensors
sensor:
  - platform: seatalk
    seatalk_id: my_seatalk
    depth:
      name: "Boat Depth"
      device_class: distance
      unit_of_measurement: m
      filters:
        - lambda: return x * -1;  # Depth is typically negative below water
    speed:
      name: "Boat Speed"
      device_class: speed
      unit_of_measurement: kn
    wind_angle:
      name: "Apparent Wind Angle"
      unit_of_measurement: "°"
    wind_speed:
      name: "Apparent Wind Speed"
      device_class: speed
      unit_of_measurement: kn
    heading:
      name: "Compass Heading"
      unit_of_measurement: "°"
    temperature:
      name: "Water Temperature"
      device_class: temperature
      unit_of_measurement: "°C"
    log_total:
      name: "Total Log"
      unit_of_measurement: "nm"

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional: Manual IP configuration
  manual_ip:
    static_ip: 192.168.1.100
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# OTA updates
ota:
  password: !secret ota_password

# Optional: Web server for debugging
web_server:
  port: 80

# Optional: Status LED
status_led:
  pin: GPIO2  # Built-in LED on many ESP8266 boards

# Optional: Text sensors for raw data (if implemented in the component)
# text_sensor:
#   - platform: seatalk
#     seatalk_id: my_seatalk
#     raw_data:
#       name: "SeaTalk Raw Data"
